version: '3'

services:
   cloud-db:
     container_name: mariadb
     image: mariadb:latest
     restart: unless-stopped
     volumes:
        - ${LOCAL_DB_DIR}:/var/lib/mysql
     env_file:
      - .env

   cloud-app:
     depends_on:
       - cloud-db
     container_name: nextcloud
     image: nextcloud:latest
     restart: unless-stopped
     volumes:
       - ${LOCAL_DATA_DIR}:/var/www/html
       - ${LOCAL_CONF_DIR}:/var/www/html/config
       - ${LOCAL_APPS_DIR}:/var/www/html/apps
     env_file:
      - .env

networks:
    default:
       external:
         name: ${NETWORK}
