version: '3'

services:
  nginx:
    image: nginx:1.15.8-alpine
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: always
    ports:
      - "{YOUR_IP}:80:80"
      - "{YOUR_IP}:443:443"
    volumes:
      - /volumes/nginx/conf.d:/etc/nginx/conf.d
      - /volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - /volumes/nginx/html:/usr/share/nginx/html
      - /volumes/nginx/certs:/etc/nginx/certs:ro
      - /volumes/nginx/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      options:
        max-size: "4m"
        max-file: "10"

  docker-gen:
    image: jwilder/docker-gen:0.7.3
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: docker-gen
    restart: always
    volumes:
      - /volumes/nginx/conf.d:/etc/nginx/conf.d
      - /volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - /volumes/nginx/html:/usr/share/nginx/html
      - /volumes/nginx/certs:/etc/nginx/certs:ro
      - /volumes/nginx/htpasswd:/etc/nginx/htpasswd:ro
      - /volumes/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      options:
        max-size: "2m"
        max-file: "10"

  letsencrypt:
    depends_on:
      - nginx
      - docker-gen
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.9.1
    container_name: letsencrypt
    restart: always
    volumes:
      - /volumes/nginx/conf.d:/etc/nginx/conf.d
      - /volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - /volumes/nginx/html:/usr/share/nginx/html
      - /volumes/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: docker-gen
      NGINX_PROXY_CONTAINER: nginx
    logging:
      options:
        max-size: "2m"
        max-file: "10"

services:
  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb:10.3.12
    restart: unless-stopped
    volumes:
      - /volumes/nextcloud-db:/var/lib/mysql
    env_file:
      - date.env

  nextcloud:
    depends_on:
      - nextcloud-db
      - letsencrypt
    container_name: nextcloud
    image: nextcloud:15.0.2
    restart: unless-stopped
    volumes:
      - /volumes/nextcloud:/var/www/html
      - /volumes/nextcloud/config:/var/www/html/config
      - /volumes/nextcloud/custom_apps:/var/www/html/custom_apps
      - /volumes/nextcloud/data:/var/www/data
    env_file:
      - date.env

networks:
  default:
    external:
       name: ssl-proxy


    env_file:
      - date.env