version: '2'

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=contraseña
      - MYSQL_PASSWORD=contraseña
      - MYSQL_DATABASE=wannacloud
      - MYSQL_USER=Wannacry

  app:
    image: nextcloud
    ports:
      - 80:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_ROOT_PASSWORD=contraseña
      - MYSQL_PASSWORD=contraseña
      - MYSQL_DATABASE=wannacloud
      - MYSQL_USER=usuario
      - NEXTCLOUD_ADMIN_USER=usuario
      - NEXTCLOUD_ADMIN_PASSWORD=contraseña
    restart:
      always

  online:
    image: libreoffice/online:master
    environment:
      domain: nube.dominio.com
      username: usuario
      password: contraseña
      extra_params: --o:ssl.enable=false
      DONT_GEN_SSL_CERT: 1
    volumes:
      - config-volume:/etc/loolwsd
    cap_add:
      - MKNOD
    ports:
      - "9980:9980"
    restart:
      unless-stopped

volumes:
  config-volume:
  nextcloud:
  db: