FROM debian:9

MAINTAINER wannaxry

RUN apt-get update
RUN apt-get install mysql-server -y
RUN mysql -u root -e "create database wannacloud"
RUN mysql -u root -e "'wannacry'@'%' identiFied by 'Atistirma_22'"
RUN mysql -u root -e "all privileges on wannacloud.* to 'wannacry'@'%'"
RUN mysql -u root -e "update mysql.user set password=PASSWORD("atistirma22") where user='wannacry'"
RUN mysql -u root -e "flush privileges"


RUN apt-get install -y nginx  
COPY nextcloud.conf /etc/nginx/sites-available
RUN ln -s /etc/nginx/sites-available/nextcloud.conf /etc/nginx/sites-enabled/   
RUN rm /etc/nginx/sites-available/default   
RUN rm /etc/nginx/sites-enabled/default  
RUN rm /var/www/html/index.nginx-debian.html 
RUN apt-get install -y php7.0 php7.0-bz2 php7.0-cli php7.0-curl php7.0-fpm php7.0-gd php7.0-intl php7.0-json php7.0-mbstring php7.0-mcrypt php7.0-mysql php7.0-opcache php7.0-sqlite3 php7.0-xml php7.0-zip php-apcu php-pear


COPY nextcloud/* /var/www/html  
RUN mkdir /var/www/html/data 
RUN chown -R www-data:www-data /var/www/html
RUN chown -R www-data:www-data /var/www/html/data
RUN find /var/www/html -type d -exec chmod 750 {} \; 
RUN find /var/www/html -type f -exec chmod 640 {} \; 
RUN find /var/www/html/data -type d -exec chmod 750 {} \; 
RUN find /var/www/html/data -type f -exec chmod 640 {} \;
RUN systemctl reload nginx